# Generated by Django 2.0.6 on 2018-11-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Enter Description')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='formaat',
            field=models.CharField(choices=[('X', 'Kies formaat'), ('G', 'Groot'), ('M', 'Normaal'), ('K', 'Klein')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='lengthcm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='lijst',
            field=models.CharField(choices=[('L', 'Ja'), ('Z', 'Nee')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='oriëntatie',
            field=models.CharField(choices=[('X', 'Kies oriëntatie'), ('L', 'Liggend'), ('S', 'Staand'), ('V', 'Vierkant'), ('D', 'Driedimensionaal')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='prijs',
            field=models.CharField(choices=[('X', 'Kies prijs'), ('B', 'Tot 499 euro'), ('M', '500 tot 999 euro'), ('H', '1000 to 2999 euro'), ('L', '3000 euro en hoger')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='prijstype',
            field=models.CharField(choices=[('X', 'Kies een prijstype'), ('B', 'Geen voorkeur'), ('K', 'Koop'), ('H', 'Huur')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='stijl',
            field=models.CharField(choices=[('X', 'Kies jouw kunststijl'), ('R', 'Realistisch'), ('I', 'Impresionistisch'), ('G', 'Gestileerd'), ('A', 'Abstract')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='techniek',
            field=models.CharField(choices=[('X', 'Kies techniek'), ('S', 'Sculptuur'), ('F', 'Fotografie'), ('D', 'Doek, Paneel'), ('P', 'Papier'), ('G', 'Grafiek'), ('D', 'Digitale techniek'), ('O', 'Overig')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='thema',
            field=models.CharField(choices=[('X', 'Kies jouw thema'), ('A', 'Architectuur'), ('D', 'Dieren'), ('E', 'Eten en Drinken'), ('L', 'Landschap en Natuur'), ('C', 'Cultuur en Land'), ('M', 'Mens en Portret'), ('O', 'Overig')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='widthcm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='kunstenaar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='products.Artist'),
        ),
    ]
