# Generated by Django 2.0.6 on 2018-11-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181116_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lengthcm',
            new_name='lcm',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='widthcm',
            new_name='wcm',
        ),
        migrations.AlterField(
            model_name='product',
            name='techniek',
            field=models.CharField(choices=[('X', 'Kies techniek'), ('S', 'Sculptuur'), ('F', 'Fotografie'), ('D', 'Doek, Paneel'), ('P', 'Papier'), ('G', 'Grafiek'), ('I', 'Digitale techniek'), ('O', 'Overig')], default='X', max_length=1),
        ),
    ]
