# Generated by Django 2.0.6 on 2018-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181116_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image2',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image3',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image4',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image5',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
